version: '3'
services:
    server:
        build: ./server
        ports:
            - 8000:8000
            - 9000:9000
        environment: 
            - MQTT_HOST=mqtt://mosquitto:1883
        networks:
            - arqui-emergentes
    sensor:
        build: ./sensor
        environment: 
            - MQTT_HOST=mqtt://mosquitto:1883
        ports:
            - 3000:3000
        networks:
            - arqui-emergentes
    mosquitto:
        build: 
            context: ./mqtt
            dockerfile: Dockerfile
        ports:
            - 1883:1883
            - 9001:9001
        networks:
            - arqui-emergentes
networks:
    arqui-emergentes: