services:
    server:
        build: ./server
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 8000:8000
            - 9000:9000
    sensor:
        build: ./sensor
        volumes:
            - ./sensor/:/usr/src/app
            - /usr/src/app/node_modules
        environment: 
            - MQTT_HOST=mqtt://mosquitto:1883
        ports:
            - 3000:3000
    mosquitto:
        build: ./mqtt
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        ports:
            - 1883:1883
            - 9001:9001
